Lodestone Row Capture Enhancement
EveryBoard/EveryBoard pull request #158
Opened 2023-11-03 20:26 UTC by MartinREMY42

2023-11-03 20:36 UTC, acieroid commented on src/app/components/game-components/game-component/GameComponent.spec.ts
> +                // deselectPressurePlate: ['top'],
code commenté

2023-11-03 20:37 UTC, acieroid commented on src/app/dao/tests/ChatDAO.spec.ts
> +xdescribe('ChatDAO', () => {
interdit !

2023-11-03 20:37 UTC, acieroid commented on src/app/games/conspirateurs/conspirateurs.component.html
> +            <circle *ngIf="square.isTherePieceToDraw"
hasPieceToDraw plutôt ?

2023-11-03 21:03 UTC, acieroid commented on src/app/games/lodestone/lodestone.component.ts
> +import { Player, PlayerOrNone } from 'src/app/jscaip/Player';
Note : quand c'est TON tour, je ne dois pas voir tes choix de lodestone (c'est une histoire de setInteractive à utiliser pour montrer les lodestone)

2023-11-03 21:33 UTC, acieroid requested changes
> Reviewed 15 of 45 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/EveryBoard/EveryBoard/158)* status: 15 of 45 files reviewed, 6 unresolved discussions (waiting on @MartinREMY42)

___
*[`src/app/games/lodestone/LodestoneRules.ts` line 36 at r1](https://reviewable.io/reviews/EveryBoard/EveryBoard/158#-NiM1WK_D8m7gXe3EHps:-NiM1WK_D8m7gXe3EHpt:b-dkxq4h) ([raw file](https://github.com/EveryBoard/EveryBoard/blob/17b46b687e89808f221e07c424ebb43b34f8570e/src/app/games/lodestone/LodestoneRules.ts#L36)):*
> ```XML
> export class LodestoneRules extends Rules<LodestoneMove, LodestoneState, LodestoneInfos> {
> 
>     public static readonly THREATENED_COORD_RANGE: PressurePlatePositionInformation = MGPMap.from({
> ```

Cette constante semble pas bien nommée non ? C'est les positions des pressure plates, pas des "threatened coords" je dirais
___
*[`src/app/games/lodestone/LodestoneRules.ts` line 274 at r1](https://reviewable.io/reviews/EveryBoard/EveryBoard/158#-NiM1nz_01l_rjKMdSk1:-NiM1nz_01l_rjKMdSk2:bh1bjgh) ([raw file](https://github.com/EveryBoard/EveryBoard/blob/17b46b687e89808f221e07c424ebb43b34f8570e/src/app/games/lodestone/LodestoneRules.ts#L274)):*
> ```XML
>                     }
>                 } else {
>                     // console.log('TODO QUOICOUBEH')
> ```

oui oui
___
*[`src/app/games/lodestone/lodestone-lodestone.component.svg` line 1 at r1](https://reviewable.io/reviews/EveryBoard/EveryBoard/158#-NiM0kRVAJlCdcq1AJQB:-NiM0kRVAJlCdcq1AJQC:b70w4n3) ([raw file](https://github.com/EveryBoard/EveryBoard/blob/17b46b687e89808f221e07c424ebb43b34f8570e/src/app/games/lodestone/lodestone-lodestone.component.svg#L1)):*
> ```SVG
> <svg:g [attr.transform]="'translate(' + (SPACE_SIZE / 2) + ' ' + (SPACE_SIZE / 2) + ')'">
> ```

Il manque la couleur du joueur propriétaire de la lodestone en son centre


<!-- Sent from Reviewable.io -->

2023-11-04 13:20 UTC, acieroid commented on src/app/games/lodestone/lodestone.component.ts
> +    public HEIGHT: number;
c'est quoi LEFT et UP ? C'est tu la viewbox ? Si oui, préférez une seule viewBox de type ViewBox plutôt que 4 variables

2023-11-04 13:21 UTC, acieroid commented on src/app/games/lodestone/lodestone.component.ts
> +        // This coord was filled after move, then crumbled after capture were placed
captures

2023-11-04 13:22 UTC, acieroid commented on src/app/games/lodestone/lodestone.component.ts
> +            (ppgi: PressurePlateGroupInfo) => ppgi.groupPosition === position,
ppgi -> info ? :D

2023-11-04 13:24 UTC, acieroid commented on src/app/games/lodestone/tests/LodestoneRules.spec.ts
> +            [_, _, O, X, _, X, O, _], // TODO FOR REVIEW EL DEOUS CHRISTOUSS
Quelle est votre question ?!

2023-11-04 13:26 UTC, acieroid commented on src/app/games/lodestone/tests/lodestone.component.spec.ts
> +            testUtils.expectElementToHaveClass('#lodestone_push_orthogonal > g > .black-fill', 'selected-stroke');
"black-fill" ça fait pas vraiment "selected" non ? (bon "outside" le faisait pas non plus)

2023-11-04 13:29 UTC, acieroid commented on src/app/games/siam/SiamPiece.ts
> -    public static readonly EMPTY: SiamPiece = new SiamPiece(0);
mais ces changements sont totalement hors scope !

2023-11-04 13:30 UTC, acieroid commented on src/app/games/siam/tests/SiamPiece.spec.ts
> +        expect(SiamPiece.DARK_DOWN.belongTo(Player.ZERO)).toBeTrue();
quoi ? Les pièces ont changés de propriétaires ? Quelle est  cette diablerie !

2023-11-04 15:13 UTC, acieroid commented on src/app/games/lodestone/tests/lodestone.component.spec.ts
> +            testUtils.expectElementToHaveClasses('#lodestone_0_0 > g > g > g > polygon', ['base', 'no-stroke', 'player1-fill']);
préférable de donner un nom de classe à l'élément et de le sélectionner moins strictement, genre `'#lodestone_0_0 .blibli` où blibli est le nom de classe donné à ce polygone. (Le `>` en CSS sélectionne parmi les enfants direct, mais si tu l'enlève ça sélectionne parmi tous les enfants je crois)

2023-11-04 15:14 UTC, acieroid commented on src/app/games/lodestone/LodestoneRules.ts
> +                plateIndex++)
mais ceci est dégueulasse monsieur !
Assigne pressurePlateLength à `newPressurePlate.getCrumbledPlates().length` et monoligne moi ça

2023-11-04 15:15 UTC, acieroid commented on src/app/games/lodestone/LodestoneState.ts
> +    public getGroupRemainingSpaces(): number {
c'est quoi un "group remaining space" ?

2023-11-15 19:22 UTC, MartinREMY42 commented on src/app/games/lodestone/lodestone.component.ts
> +import { Player, PlayerOrNone } from 'src/app/jscaip/Player';
Saint-Severin, voleur d'idiées !

2023-11-23 20:45 UTC, MartinREMY42 commented on src/app/games/lodestone/lodestone.component.ts
> +            (ppgi: PressurePlateGroupInfo) => ppgi.groupPosition === position,
hein :D ? pourquoi ça :D ?

2023-11-23 20:46 UTC, MartinREMY42 commented on src/app/games/lodestone/tests/LodestoneRules.spec.ts
> +            [_, _, O, X, _, X, O, _], // TODO FOR REVIEW EL DEOUS CHRISTOUSS
c'est toi qui l'avais fait ou moi ? c'est drol.
TPR.

2023-12-13 00:18 UTC, acieroid commented on src/app/components/game-components/game-component/GameComponent.spec.ts
> +            // Instead:
yes faut les supprimer alors !

2023-12-13 00:27 UTC, acieroid commented on src/app/games/lodestone/lodestone.component.ts
> +        this.platesGroupSize = abstractPlateWidth * (this.SPACE_SIZE * 1.2);
non, un .get ne devrait pas changer des variables ! c'est plutôt à calculer dans updateState, de même que boardSize 3 lignes plus bas

2023-12-13 00:30 UTC, acieroid commented on src/app/games/lodestone/lodestone.component.ts
> +            (ppgi: PressurePlateGroupInfo) => ppgi.groupPosition === position,
Genre que le nom de la classe devient tellement long que si tu veux fitter sur 80 caractères tu dois abbrévier :p 
`HelperCallbackPredicateServerBroadcasterVisitorServiceFacadeListWatcherDatabase` -> `HelperCPSBVSFLWD` !

2023-12-13 00:30 UTC, acieroid commented on src/app/games/lodestone/lodestone.component.ts
> +            (ppgi: PressurePlateGroupInfo) => ppgi.groupPosition === position,
(tpr)

2023-12-13 00:31 UTC, acieroid commented on src/app/games/lodestone/tests/LodestoneRules.spec.ts
> +            [_, _, O, X, _, X, O, _], // TODO FOR REVIEW EL DEOUS CHRISTOUSS
je pense que c'est moi, peut-être volontairement pour voir si t'allais la catcher  à la review ! faut blame pour savoir :p Mais j'te laisse résoudre

2023-12-13 00:32 UTC, acieroid commented on src/app/games/lodestone/tests/lodestone.component.spec.ts
> +            testUtils.expectElementToHaveClass('#lodestone_push_orthogonal > g > .black-fill', 'selected-stroke');
poussé mais pas changé !

2023-12-13 00:34 UTC, acieroid commented on src/app/games/siam/tests/SiamPiece.spec.ts
> +        // TODO FOR REVIEW: Haha, on avait confondu ZERO ET ONE, ou plutôt DARK ET LIGHT, qui est qui, je crois, mais yavais stuutage dans l'air
abinwinw effectivement, bien vu ! Tu peux enlever les TODO et plusser !

2023-12-13 00:35 UTC, acieroid commented on src/app/games/lodestone/LodestoneState.ts
> +    public getGroupRemainingSpaces(): number {
tu n'expliques pas et ne change rien :D

2023-12-13 00:51 UTC, acieroid commented on src/app/dao/tests/ChatDAO.spec.ts
> +xdescribe('ChatDAO', () => {
toujours interdit ! Mais TPR en somme vu que ceci casse les tests donc c'est inmergeable tant que c'est présent

2023-12-13 00:57 UTC, acieroid commented on src/app/games/lodestone/LodestoneState.ts
> +    public static getNew(sizes: number[]): LodestonePressurePlateGroup {
.from ou .of comme nom à la place par conventionnalité ?

2023-12-13 00:59 UTC, acieroid commented on src/app/games/lodestone/LodestoneState.ts
> +    public getGroupRemainingSpaces(): number {
ah c'est commenté, bene ! T'sais tu juste rajouter un petitos commentaire au dessus de la classe qui dit « une LodestonePressurePlateGroup c'est plusieurs pressure plate ensemble », j'avais pas capté tout de suite (en partie parce que le diff de github était de la couille pas possible)

2023-12-13 01:00 UTC, acieroid commented on src/app/games/lodestone/LodestoneState.ts
> +        const totalRemainingSpaces: number = remainingSpaces.reduceRight((left: number, right: number) => left + right);
eh, reduce est bon, pas besoin de forcer le sens !

2023-12-13 01:21 UTC, acieroid commented on translations/messages.fr.xlf
> +        <target>Le but du Siam est d&apos;être le premier à pousser une montagne hors du plateau. Le plateau de départ en contient trois, au centre, et aucun pion n&apos;est initialement sur le plate
j'imagine t'as juste coupé les lignes et pas changé le texte HEIN (sinon joie ô joie pour savoir ce qui a réellement changé :D)

2023-12-13 01:23 UTC, acieroid commented on src/app/games/lodestone/tests/lodestone.component.spec.ts
> +            testUtils.expectElementToHaveClass('#square_0_0 > polyline', 'moved-fill');
pour être plus méta on pourrait nommer par des classes certains éléments, avec des classes qui seraient pas utilisées pour le css mais pour les tests, ainsi on dirait « et leur contour est moved-fill » plutôt que « leur polyline est moved-fill », ce qui est changement-résistant si on passe d'une polyline à autre chose, tant qu'on dit c'est quoi le contour

2023-12-13 18:49 UTC, MartinREMY42 commented on src/app/games/lodestone/tests/lodestone.component.spec.ts
> +            testUtils.expectElementToHaveClass('#lodestone_push_orthogonal > g > .black-fill', 'selected-stroke');
Quoi tu veux remettre une classe outside qui ne sert à rien cssement mais rends ça joli ?

2023-12-13 19:11 UTC, MartinREMY42 commented on translations/messages.fr.xlf
> +        <target>Le but du Siam est d&apos;être le premier à pousser une montagne hors du plateau. Le plateau de départ en contient trois, au centre, et aucun pion n&apos;est initialement sur le plate
Normalement, oui ! Prions :D

2023-12-14 12:50 UTC, acieroid commented on src/app/games/lodestone/tests/lodestone.component.spec.ts
> +            testUtils.expectElementToHaveClass('#square_0_0 > polyline', 'moved-fill');
`nom-du-jeu_description`, genre `lodestone_contour` ?

2023-12-14 12:51 UTC, acieroid commented on src/app/games/lodestone/LodestoneState.ts
> +    public getGroupRemainingSpaces(): number {
non fait

2023-12-16 13:13 UTC, acieroid approved these changes

2023-12-16 14:54 UTC, acieroid commented on src/app/games/lodestone/lodestone.component.ts
>      private updateViewInfo(): void {
quelques soucis : après un mouvement reçu où des pièces ont été capturées et placée sur les pressure plates :
  - je sélectionne ma lodestone: les pièces sur les pressure plates ne sont plus montrées en last-moved
  - je désélectione ma lodestone: plus rien n'est montré en last moved
  - je clique n'importe où d'autre: tout est montré comme qu'il faut en last moved

2023-12-19 19:11 UTC, acieroid commented on src/app/games/lodestone/lodestone.component.ts
>      private updateViewInfo(): void {
+ appliquer le même comportement au sélectionnage de case

2023-12-19 19:14 UTC, acieroid commented on src/app/games/lodestone/lodestone.component.ts
>      private updateViewInfo(): void {
+ bug de viewbox

2023-12-23 00:22 UTC, acieroid commented on src/app/games/lodestone/tests/lodestone.component.spec.ts
> +        it('selecting coord should hide last move ', fakeAsync(async() => {
should hide last move when selecting coord

2023-12-23 00:24 UTC, acieroid commented on src/app/games/lodestone/tests/lodestone.component.spec.ts
> +        it('selecting coord should hide last move ', fakeAsync(async() => {
+ reste le bug polyline (cf. trello)

2023-12-23 21:51 UTC, merged