[CurrentPlayerMustBeBellow] adapted online-game-wrapper component so …
EveryBoard/EveryBoard pull request #45
Opened 2022-08-24 09:24 UTC by MartinREMY42

…that player is always below for the game needing it

2022-08-25 15:35 UTC, acieroid requested changes

2022-08-25 16:11 UTC, MartinREMY42 commented on src/app/components/game-components/game-component/GameComponent.ts
> +                @Inject(Boolean) public readonly mustRotateBoard: boolean)
haha, c'est que des classes d'habitudes, les params d'un constructeur de composant, donc, injectable, pour le booléen bizarrement pas, donc voici cette horreur apparemment non négociable :D

2022-08-25 16:12 UTC, MartinREMY42 commented on src/app/components/wrapper-components/online-game-wrapper/online-game-wrapper.component.ts
> +        }
haha, bah c'est cool hein, après no-early-celebration, c'est pas encore testé en profondeur :D !

2022-08-25 16:13 UTC, MartinREMY42 commented on src/app/games/epaminondas/epaminondas.component.ts
> +        super(messageDisplayer, true);
une convention sur qui est où sur le plateau ? Genre, retourner systématiquement ?

2022-08-25 16:14 UTC, MartinREMY42 commented on src/app/games/kamisado/kamisado.component.html
> +      [attr.transform]="rotation"
la plateau de départ ? Pour quoi faire ?
Mapper les state.board et tout ?

2022-08-25 16:27 UTC, acieroid commented on src/app/games/kamisado/kamisado.component.html
> +      [attr.transform]="rotation"
bah non juste placer les pièces dans le sens conventionnel où joueur 0 est en bas. En gros rien changer dans le code ni dans l'affichage, juste avoir un .getInitialBoard() qui nous donne le bon plateau !

2022-08-25 16:28 UTC, acieroid commented on src/app/games/epaminondas/epaminondas.component.ts
> +        super(messageDisplayer, true);
La convention du « premier joueur est en bas », ainsi pas besoin de ce booléen qui serait toujours à faux. Car là ça fait vraiment vieille rustine pour pas corriger la source du problème en fait :o

2022-08-25 16:29 UTC, acieroid commented on src/app/components/game-components/game-component/GameComponent.ts
> +                @Inject(Boolean) public readonly mustRotateBoard: boolean)
de toute façon faut arriver à pas avoir besoin de ce booléen :D (cf. les commentaires suivants)

2022-08-25 18:59 UTC, MartinREMY42 commented on src/app/games/epaminondas/epaminondas.component.ts
> +        super(messageDisplayer, true);
Y a pas de convention du premier joueur en bas, c'est précisément l'objectif de ce ticket que le joueur en bas n'aie soit pas de sens car y a pas un vrai "bas" (au mieux t'as plus de pièces au joueur zéro en bas au début, mais c'est pas vraiment "en bas") au pire bah y a une orientation, et la convention c'est JE SUIS en bas (et ça, c'est ce que j'ai fait pour les trois jeux à orientations, epaminondas, awalé, kamisado.

2022-08-25 19:01 UTC, MartinREMY42 commented on src/app/games/kamisado/kamisado.component.html
> +      [attr.transform]="rotation"
ah comme ça, oui somme toute ça a du sens mais là, comme y a une orientation à ces trois jeux (dont le joueur zéro est PAS en bas, c'est vrai) juste inverser le plateau initial rendrait quand même dégueux le fait de jouer le second joueur (au lieu de rendre pourri le premier)

2022-08-26 16:38 UTC, acieroid requested changes

2022-08-26 16:38 UTC, acieroid commented on src/app/components/wrapper-components/online-game-wrapper/online-game-wrapper.component.ts
> +        }
je pense que cette ligne ajoute une branche non couverte au vu de l'erreur de CI !

2022-08-26 16:57 UTC, acieroid commented on src/app/components/wrapper-components/online-game-wrapper/online-game-wrapper.component.ts
> +        }
et voir la conflictualité sur observerRole, mais on verra en temps de merge, si ça se trouve c'est trivial (un .value lo, mais ça risque de faire du 360)

2022-08-26 17:42 UTC, acieroid commented on src/app/games/kamisado/kamisado.component.html
> +      [attr.transform]="rotation"
je dirais oui à la convention premier joueur en bas !
Pour le reste c'est plus clair post-discussion

2022-08-26 17:45 UTC, acieroid commented on src/app/components/game-components/game-component/GameComponent.ts
> +                @Inject(Boolean) public readonly mustRotateBoard: boolean)
qui d'avoir un public mustRotateBoard: boolean = false; et de le définir à true dans les constructeurs qui en ont besoin? Un peu comme tous les autres champs du GameComponent en fait, ceux qui n'ont pas besoin d'être injectés ! (this.scores, this.encoder et consorts)

2022-08-28 13:23 UTC, MartinREMY42 commented on src/app/components/game-components/game-component/GameComponent.ts
> +                @Inject(Boolean) public readonly mustRotateBoard: boolean)
C'mieux lo !

2022-09-07 05:51 UTC, MartinREMY42 commented on src/app/components/wrapper-components/online-game-wrapper/online-game-wrapper.component.ts
> +        }
haha oui, les observeur le verrons avec un 360°, faudra leur demander si ça leur fait pas mal à la nuque lors des tests ux :P !

2022-09-07 05:52 UTC, MartinREMY42 commented on src/app/games/kamisado/kamisado.component.html
> +      [attr.transform]="rotation"
Implémenté pour l'awalé, le seul des jeux orienté qui y contrevenait !

2022-09-07 06:32 UTC, acieroid commented on src/app/components/normal-component/welcome/welcome.component.ts
> +    public readonly numberOfColumns: number = 5;
T'AS TU FAIT VALIDER CE CHANGEMENT MAJEUR D'UX PAR DES PROFESSIONNELS ? :D

2022-09-07 06:32 UTC, acieroid commented on src/app/components/wrapper-components/GameWrapper.ts
> +        this.gameComponent.observerRole = this.observerRole;
err son grand retour, peut-être en profiter pour lui donner un nom adapté ? :D

2022-09-07 06:37 UTC, acieroid commented on src/app/components/wrapper-components/online-game-wrapper/online-game-wrapper.reversable.component.spec.ts
> +    it('Should have a rotation not applied for player one', fakeAsync(async() => {
en gros les 131 premières lignes de ce fichier c'est du copy-pasta de l'autre ? Y'aurais pas moyen d'éviter ça, surtout qu'en plus ça fait un TODO en plus qui a été copié !

2022-09-07 06:37 UTC, acieroid commented on src/app/components/wrapper-components/online-game-wrapper/online-game-wrapper.reversable.component.spec.ts
> +
extra newline

2022-09-07 06:39 UTC, MartinREMY42 commented on src/app/components/normal-component/welcome/welcome.component.ts
> +    public readonly numberOfColumns: number = 5;
Euuuuh, non, changement de mood, c'est pour indiquer qu'on s'approche de la V1 :D !

2022-09-07 06:40 UTC, MartinREMY42 commented on src/app/components/wrapper-components/GameWrapper.ts
> +        this.gameComponent.observerRole = this.observerRole;
playerOrNone :D ? 
playingRole ?
Après il a été partit pas très longtemps, c't'un petit retour :D

2022-09-11 18:58 UTC, MartinREMY42 commented on src/app/components/wrapper-components/online-game-wrapper/online-game-wrapper.quarto.component.spec.ts
> +    // let configRoomDAO: ConfigRoomDAO;
jeeeee suis un pain à la banane ?

2022-09-11 18:59 UTC, MartinREMY42 commented on src/app/components/wrapper-components/online-game-wrapper/online-game-wrapper.reversable.component.spec.ts
> +    it('Should have a rotation not applied for player one', fakeAsync(async() => {
quoi ?

2022-09-11 19:00 UTC, MartinREMY42 commented on src/app/components/wrapper-components/online-game-wrapper/online-game-wrapper.quarto.component.spec.ts
> +    return { t: testUtils, o: observerRole, p: partDAO };
En vrai brève question, _testUtils: testUtils ça te va ? J'me sent pas de leur donner le même nom que la variable dans laquelle ça finit, sauf si tu crois que c'est la meilleurs idée si tant est que c'est possible ?
J'suis pas expert dans ce système là.

2022-09-12 06:55 UTC, acieroid commented on src/app/components/wrapper-components/online-game-wrapper/online-game-wrapper.quarto.component.spec.ts
> +    return { t: testUtils, o: observerRole, p: partDAO };
bah c'est le mieux de leur donner le même nom non ?
Ainsi tu fais:
```
const result = prepareBli()`
testUtils = result.testUtils;
```
Pourquoi ça serait plus clair avec `t` ou `_testUtils`?

2022-09-12 07:02 UTC, acieroid commented on src/app/components/wrapper-components/online-game-wrapper/online-game-wrapper.reversable.component.spec.ts
> +    it('Should have a rotation not applied for player one', fakeAsync(async() => {
pas avoir `t`, `o`, etc. comme nom de champ !

2022-09-12 17:08 UTC, MartinREMY42 commented on src/app/components/wrapper-components/online-game-wrapper/online-game-wrapper.quarto.component.spec.ts
> +    return { t: testUtils, o: observerRole, p: partDAO };
ouais mais faut typer result avec un truc à rallonge assez dégolosse que je préfère n'écrire qu'une fois.

2022-09-12 17:56 UTC, acieroid commented on src/app/components/wrapper-components/online-game-wrapper/online-game-wrapper.quarto.component.spec.ts
> +    return { t: testUtils, o: observerRole, p: partDAO };
bah tu fais
```
type PreparationResult = { testUtils: ComponentBli, role: Player }
```
Et tu dois pas le taper moulte fois !

2022-09-12 17:57 UTC, acieroid commented on src/app/components/wrapper-components/online-game-wrapper/online-game-wrapper.quarto.component.spec.ts
> +: Promise<{ _testUtils: ComponentTestUtils<T, MinimalUser>, _role: PlayerOrNone }>
sans le alstub? :D

2022-09-12 17:57 UTC, acieroid commented on src/app/components/wrapper-components/online-game-wrapper/online-game-wrapper.quarto.component.spec.ts
> +        const { _testUtils, _role } = (await prepareStartedGameFor<QuartoComponent>(authUser,
trche de non typage !

2022-10-10 19:46 UTC, acieroid commented on src/app/components/wrapper-components/GameWrapper.ts
> +            console.log('here then we rotate like so', this.gameComponent.rotation)
conzole

2022-10-10 19:47 UTC, acieroid commented on src/app/components/game-components/game-component/GameComponent.ts
> +    public rotation: string = '';
peut-être documenter avec un commentaire d'une ligne précédent ces variables ?
(ce que ça représente, à quoi ça sert, si c'est un point de configuration, etc.)

2022-10-10 19:48 UTC, acieroid commented on src/app/components/wrapper-components/local-game-wrapper/local-game-wrapper.component.ts
> +import { Player, PlayerOrNone } from 'src/app/jscaip/Player';
remove this  import !

2022-10-10 19:48 UTC, acieroid commented on src/app/components/wrapper-components/local-game-wrapper/local-game-wrapper.component.ts
> +        console.log('update player ' + player.toString() + ' with [' + this.playerSelection[0] + ', ' + this.playerSelection[1] + ']');
svp

2022-10-10 19:48 UTC, acieroid commented on src/app/components/wrapper-components/online-game-wrapper/online-game-wrapper.component.ts
> +    // }
rrrrriiiiii

2022-10-10 19:49 UTC, acieroid commented on src/app/components/wrapper-components/online-game-wrapper/online-game-wrapper.quarto.component.spec.ts
> +
pas convaincu de l'apport de lisibilité de cet espace

2022-10-10 19:50 UTC, acieroid commented on src/app/components/wrapper-components/online-game-wrapper/online-game-wrapper.reversable.component.spec.ts
> +    it('Should have a rotation not applied for player one', fakeAsync(async() => {
should not Should !

2022-10-10 19:51 UTC, acieroid commented on src/app/components/wrapper-components/online-game-wrapper/online-game-wrapper.reversable.component.spec.ts
> +        // Given a game started for opponent (player two)
keuwa on a un player two maintenant ? (x two)

2022-10-10 19:52 UTC, acieroid commented on src/app/components/wrapper-components/tutorial-game-wrapper/tutorial-game-wrapper.games.component.spec.ts
> +        fit('Should make sure that predicate step have healthy behaviors', fakeAsync(async() => {
камолосо !

2022-10-11 16:48 UTC, MartinREMY42 commented on src/app/components/wrapper-components/online-game-wrapper/online-game-wrapper.component.ts
> +    // }
Riz ?

2022-10-11 16:50 UTC, MartinREMY42 commented on src/app/components/wrapper-components/online-game-wrapper/online-game-wrapper.quarto.component.spec.ts
> +
Mmh je doute aussi, dans ce cas là.

2022-10-11 16:52 UTC, MartinREMY42 commented on src/app/components/wrapper-components/online-game-wrapper/online-game-wrapper.reversable.component.spec.ts
> +        // Given a game started for opponent (player two)
no longer !

2022-10-11 16:52 UTC, MartinREMY42 commented on src/app/components/wrapper-components/tutorial-game-wrapper/tutorial-game-wrapper.games.component.spec.ts
> +        fit('Should make sure that predicate step have healthy behaviors', fakeAsync(async() => {
haha, le fameux cyrillique danois !

2022-10-11 16:55 UTC, MartinREMY42 commented on src/app/games/martian-chess/tests/MartianChessRules.spec.ts
> +        const move: MartianChessMove = MartianChessMove.from(new Coord(1, 7), new Coord(0, 7)).get();
à part "deux pas horizontal" tout est encodé, les 8 cases voisines sont accessible et les puis cases à distance (2n, 2n) voisine aussi si (n, n) l'était. tu veux un test en plus, les noms étaient pourrites dans les test du drone.

2022-10-14 18:47 UTC, acieroid approved these changes

2022-10-14 19:14 UTC, merged