[SaharaShowPossibleLanding] done
EveryBoard/EveryBoard pull request #46
Opened 2022-08-25 19:32 UTC by MartinREMY42

2022-08-26 06:11 UTC, acieroid requested changes

2022-08-26 06:11 UTC, acieroid commented on src/app/games/sahara/sahara.component.ts
> +            this.possibleLandings = this.rules.getLandingsCoords(this.board, coord);
getLandingCoords ou getLandings mais pas les deux !

2022-08-26 06:11 UTC, acieroid commented on src/app/games/sahara/SaharaRules.ts
> +        const isInBoardAndEmpty: (coord: Coord) => boolean = (coord: Coord) => {
isOnBoardAndEmpty?
Et est-ce que que getNeighbors devrait pas retourner que des voisins sur le plateau déjà ? (si c'est pas le cas, peut-être fixer à cet endroit plutôt que de filtrer par après ?)

2022-08-26 06:11 UTC, acieroid commented on src/app/games/sahara/SaharaRules.ts
> +                const secondStepNeighbors: Coord[] =
tu risques pas de te retrouver avec des doublons là ?

2022-08-26 06:11 UTC, acieroid commented on src/app/games/sahara/SaharaRules.ts
> +            console.log(twoStepJump.concat(neighbors))
log is forbidden x2

2022-08-26 06:11 UTC, acieroid commented on src/app/games/sahara/SaharaMove.ts
> +            if (TriangularCheckerBoard.isSpaceDark(start)) {
fonction à utiliser dans coerceo également ? :o

2022-08-26 20:49 UTC, MartinREMY42 commented on src/app/games/sahara/SaharaRules.ts
> +        const isInBoardAndEmpty: (coord: Coord) => boolean = (coord: Coord) => {
Non non, car TriangularThingy sais pas la taille du plateau

2022-08-26 20:55 UTC, MartinREMY42 commented on src/app/games/sahara/SaharaRules.ts
> +                const secondStepNeighbors: Coord[] =
plus maintenant (voir lignes non incriminées plus loin)

2022-08-26 20:57 UTC, MartinREMY42 commented on src/app/games/sahara/SaharaMove.ts
> +            if (TriangularCheckerBoard.isSpaceDark(start)) {
peut être, on le sais pour plus tard, mais coercoe se base p-e sur le déplacement des pièces, et pas leur atterrissage!

2022-08-29 06:59 UTC, acieroid requested changes

2022-08-29 06:59 UTC, acieroid commented on src/app/games/sahara/SaharaRules.ts
> +        const isInBoardAndEmpty: (coord: Coord) => boolean = (coord: Coord) => {
Ok pour ça, mais t'as pas changé le nom !

2022-08-29 06:59 UTC, acieroid commented on src/app/games/sahara/SaharaRules.ts
> +                const secondStepNeighbors: Coord[] =
hmm pourquoi pas utiliser un set directement pour `twoStepJump`? Plutôt que d'accumuler les doublons pour les supprimer, autant les supprimer direct

2022-08-29 06:59 UTC, acieroid commented on src/app/games/sahara/tests/sahara.component.spec.ts
> +    it('should show possible landing when selecting a piece', fakeAsync(async() => {
landings

2022-09-05 18:37 UTC, acieroid commented on src/app/games/sahara/SaharaRules.ts
> +                twoStepJump.add(neighbor);
pourquoi ne pas faire le .add deux lignes avant et éviter de double for sur la même collection ?

2022-09-06 05:53 UTC, acieroid approved these changes

2022-09-08 15:55 UTC, acieroid requested changes

2022-09-12 05:24 UTC, MartinREMY42 commented on src/app/games/sahara/tests/sahara.component.spec.ts
> +    it('should show possible landings when selecting a piece', fakeAsync(async() => {
allez, j'ajoute celui là aussi c'est vrai.

2022-09-12 06:42 UTC, acieroid approved these changes

2022-09-12 06:44 UTC, merged